# PROJECT OF PANDAS AND NUMPY EVALUATION ON DATAQUEST.IO

The dataset to be studied is a dataset frome *eBay Kleinanzeigen*. It is a classified section of the German eBay website. The dataset contains used cars information.

The dataset, at first was downloaded from Kaggle. However, the Dataquest.io team has done two things to the dataset:

- First of all, they have sampled the dataset in order to make the code faster to run.
- Secondly, they have dirted the dataset. Originally, the dataset uploaded on [kaggle](https://www.kaggle.com/orgesleka/used-cars-database/data) was cleaned. So they have dirted in order to put in practice the things learned on the course.

## 1. Dataset Structure

The data dictionary provided is as follows:

* `dateCrawled` - When the ad was firs crawled.
* `name` - Name of the car.
* `seller` - Whether the seller is private or a dealer.
* `offerType` - The type of listing.
* `price` - The price on the ad to sell the car.
* `abtest` - Whether the listing is included in an A/B test.
* `vechicleType` - The vehicle type.
* `yearOfRegistration` - The year in which the car was first registered.
* `gearbox` - The transmission type.
* `powerPS` - The power of the car in PS.
* `model` - The car model name.
* `kilometer` - How many kilometers the car has driven.
* `monthOfRegistration` - The month in which the car was first registered.
* `fuelType` - What type of fuel the car uses.
* `brand` - The brand of the car.
* `notRepairedDamage` - If the car has a damage which is not yet repaired.
* `dateCreated` - The date on which the eBay listing was created.
* `nrOfPictures` - The number of pictures in the ad.
* `postalCode` - The postal code for the location of the vehicle.
* `lastSeenOnline` - When the crawler saw this ad last time.

## 2. Objective of the project

The aim of this project is to clean the data and analyze the included used car listings.

## 3. Process

### 3.1. Import the libraries

First of all, in order to clean control the dataset, the essential libraries are downloaded

In [1]:
import numpy as np #Numpy library
import pandas as pd #Pandas library

#Read the csv. As the UTF-8 default encoding does not work, Latin-1
#encoding is used.
autos = pd.read_csv('autos.csv' , encoding = 'Latin-1') 

#Some lines of code for checking the dataset
#shp = autos.shape
#print(autos.head())
#print(shp)

### 3.2. Dataset checking

In [2]:
autos #Pandas dataframe of the dataset

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [3]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

On the previous cell we have checked the information of the columns. Here we can see some things:

- The dataset has 20 columns which most of them are strings.

- The column names use camelcase .

- There are some columns which contain null values, as the numer of non-null elements is smaller than 50 thousand.

- Another point is that some columns consist of object data. Which means that are strings. Whereas some columns such as `yearOfRegistration` is a series of integers.

In order to clean the data, there has to be checked the null data if there can be something done. An check if there is a string based series which would be better an integer or a float.

### 3.3. Edition of the column names

Firs of all the column names will be print.

In [4]:
column_names = autos.columns
print(column_names)

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

A copy of the array is performed for editting the column names. Careful executing only once the following cell. If you execute more than once, it won't work. This is because the names would be changed already.

The dataframe.rename method checks the column name in this case and changes it according to the dictionary. However, if the code is executed once. All the names will be changed. Because of this, on the second execution no column name would be equal to the keys of the dictionary, so the code will give you an error.

In [5]:
#column_names_copy = column_names.copy() #Copy is done

#The names of the columns are renamed
autos.rename(
             {'yearOfRegistration' : 'registration_year' ,
              'monthOfRegistration' : 'registration_month',
              'notRepairedDamage' : 'unrepaired_damage' ,
              'dateCreated' : 'ad_created' ,
              'dateCrawled' : 'date_crawled' ,
              'offerType' : 'offer_type' ,
              'vehicleType' : 'vehicle_type' ,
              'powerPS' : 'power_ps' ,
              'fuelType' : 'fuel_type' ,
              'nrOfPictures' : 'num_pictures' ,
              'postalCode' : 'postal_code' ,
              'lastSeen' : 'last_seen' ,
             } , 
             axis = 1 ,
             inplace = True)

In [6]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

A seen on the tabe above, all the column names have been changed.

### 3.4. Data exploration

Some data exploration must be done in order to see if other cleaning steps need to be done or not:

- Text columns where all or almost all values are the same. Sometimes, those could be dropped as they don't have useful information for analysis.

- Numeric data sorted as text which can be cleaned and converted.

In [7]:
autos.describe(include = 'all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-30 19:48:02,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

As can be seen on the table above some insight:

- The `seller`column has only two values (*private* and *public*), only one time has the value *public*.
- Same happens with `offer_type` column wich only once has a value different to *Angebot*.
- The `num_pictures` columns looks odd. Further investigation has to ve performed.

In [8]:
autos.loc[: , 'num_pictures'].value_counts()

0    50000
Name: num_pictures, dtype: int64

The cell above tells that there is no ad with pictures on the database. So this column can be taken out too.

In [9]:
autos = autos.drop(labels = ['seller' , 'offer_type' , 'num_pictures'] ,
           axis = 1)

The non-interesting data has been taken out. However there are some columns which show interesting data, and they are stored as strings:

- `date_crawled` - It is stored as string, but it should be stored as numpy datetime.
- `price` - It is stored as string because it has the dollar symbol. There has to be taken out the dollar symbol, save the column as integer, and change the column name to price_dollar.
- `odometer` - This column shows the kilometers performed. It is stored as string. Similar as price, the km has to be taken out and the column name renamed to odometer_km.
- `registration_month` stored as float. It should be stored as datetime.
- `ad_created` is stored as string. Has to be stored as datetime too.
- `last_seen` is stored as string. Has to be stored as datetime.

Let's start cleaning the `price` and `odometer` columns.

In [10]:
autos.loc[: , 'price'] = autos.loc[: , 'price'].str.replace('$' , '').str.replace(',','').astype(int)

In [11]:
print(autos.dtypes)

date_crawled          object
name                  object
price                  int64
abtest                object
vehicle_type          object
registration_year      int64
gearbox               object
power_ps               int64
model                 object
odometer              object
registration_month     int64
fuel_type             object
brand                 object
unrepaired_damage     object
ad_created            object
postal_code            int64
last_seen             object
dtype: object

As we can see on the table above, the price is already an integer. Let's rename the column name.

In [12]:
autos.rename({'price' : 'price_dollar'} , axis = 1 , inplace = True)

In [13]:
print(autos.dtypes)

date_crawled          object
name                  object
price_dollar           int64
abtest                object
vehicle_type          object
registration_year      int64
gearbox               object
power_ps               int64
model                 object
odometer              object
registration_month     int64
fuel_type             object
brand                 object
unrepaired_damage     object
ad_created            object
postal_code            int64
last_seen             object
dtype: object

Let's do the same with the column `odometer`.

In [14]:
autos.loc[: , 'odometer'] = autos.loc[: , 'odometer'].str.replace(',' , '').str.replace('km' , '').astype(int)

In [15]:
autos.rename({'odometer' : 'odometer_km'} , axis = 1 , inplace = True)

In [16]:
print(autos.dtypes)

date_crawled          object
name                  object
price_dollar           int64
abtest                object
vehicle_type          object
registration_year      int64
gearbox               object
power_ps               int64
model                 object
odometer_km            int64
registration_month     int64
fuel_type             object
brand                 object
unrepaired_damage     object
ad_created            object
postal_code            int64
last_seen             object
dtype: object

### 3.5. Analyzing the odometer_km and price_dollar columns

First of all we are going to check the values of the columns. Analyzing the maximum and the minimum value of the columns.

In [17]:
autos.describe()

,price_dollar,registration_year,power_ps,odometer_km,registration_month,postal_code
count,5.000000e+04,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,9.840044e+03,2005.073280,116.355920,125732.700000,5.723360,50813.627300
std,4.811044e+05,105.712813,209.216627,40042.211706,3.711984,25779.747957
min,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,1067.000000
25%,1.100000e+03,1999.000000,70.000000,125000.000000,3.000000,30451.000000
50%,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,49577.000000
75%,7.200000e+03,2008.000000,150.000000,150000.000000,9.000000,71540.000000
max,1.000000e+08,9999.000000,17700.000000,150000.000000,12.000000,99998.000000

In the case of the price column we there are vehicles which cost 0 dollars and others which coste 1e8.

In [18]:
print(autos.loc[: , 'price_dollar'].unique().shape)

(2357,)

As it can be checked on the cell above, there are 2374 unique values on the price column. Let's check which ones are.

In [19]:
autos.loc[: , 'price_dollar'].value_counts().head(20)

0       1421
500      781
1500     734
2500     643
1000     639
1200     639
600      531
800      498
3500     498
2000     460
999      434
750      433
900      420
650      419
850      410
700      395
4500     394
300      384
2200     382
950      379
Name: price_dollar, dtype: int64

In the cell above, is easy to check that there are 1421 cars which value is 0 dollars. That could not be possible. Let's check if 1421 is a big amount of data or not.

In [20]:
percentage = 1421 / 50000 * 100
print('The percentage of 0 values is: ' + str(percentage) + '%')

The percentage of 0 values is: 2.842%

Let's check what happens on the other side of the column. I mean on the highest values of prices.

In [21]:
autos.loc[: , 'price_dollar'].value_counts().sort_index(ascending = False).head(20)

99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
350000      1
345000      1
299000      1
295000      1
265000      1
259000      1
250000      1
220000      1
198000      1
197000      1
Name: price_dollar, dtype: int64

There are about 15 rows that are bigger than 1M dollars. This is not a real price for a car.

In the case of the price column, there are over 1500 cars with the value of 0 dollar, which is inconsistent. As eBay is a biding web, the bids could start from 1$, but not from 0.

Whereas on the other side, there are more or less 15 cars which cost is over a million dollars. That is impossible. So there hast to be put some limits.

The uper limit would be 350k dollars, as the numbers seem to be more realistic. On the lower limit, it would be 1 dollar.

In [22]:
autos = autos.loc[ (autos.loc[: , 'price_dollar'] > 0 ) & (autos.loc[: , 'price_dollar'] <= 350000), :]

In [23]:
autos.describe()

,price_dollar,registration_year,power_ps,odometer_km,registration_month,postal_code
count,48565.000000,48565.000000,48565.000000,48565.000000,48565.000000,48565.000000
mean,5888.935591,2004.755421,117.197158,125770.101925,5.782251,50975.745207
std,9059.854754,88.643887,200.649618,39788.636804,3.685595,25746.968398
min,1.000000,1000.000000,0.000000,5000.000000,0.000000,1067.000000
25%,1200.000000,1999.000000,71.000000,125000.000000,3.000000,30657.000000
50%,3000.000000,2004.000000,107.000000,150000.000000,6.000000,49716.000000
75%,7490.000000,2008.000000,150.000000,150000.000000,9.000000,71665.000000
max,350000.000000,9999.000000,17700.000000,150000.000000,12.000000,99998.000000

As can be checked, the price of the cars now is between 350k dollars and 1 dollar.

Let's check what happens with the odometer column.

In [24]:
print(autos.loc[: , 'odometer_km'].unique().shape)

(13,)

There are only 13 unique values on the odometer. That means that the data has been rounded.

In [25]:
autos.loc[: , 'odometer_km'].unique()

array([150000,  70000,  50000,  80000,  10000,  30000, 125000,  90000,
        20000,  60000,   5000, 100000,  40000])

In [26]:
autos.loc[: , 'odometer_km'].value_counts()

150000    31414
125000     5057
100000     2115
90000      1734
80000      1415
70000      1217
60000      1155
50000      1012
5000        836
40000       815
30000       780
20000       762
10000       253
Name: odometer_km, dtype: int64

Checking the unique values of the odometer. There are not any strange value. So it would be let as it is.

### 3.6. Date columns

There are 5 columns that should represent date values:

- `dataset_crawled` - Added by the crawler.
- `last_seen` - Added by the crawler.
- `ad_created` - From the website.
- `registration_month` - From the website.
- `registration_year` - From the website.

As you would check, some data has been obtained from the crawler and some from the website itself.

In [27]:
autos.describe(include ='all')

,date_crawled,name,price_dollar,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
count,48565,48565,48565.000000,48565,43979,48565.000000,46222,48565.000000,46107,48565.000000,48565.000000,44535,48565,39464,48565,48565.000000,48565
unique,46882,37470,NaN,2,8,NaN,2,NaN,245,NaN,NaN,7,40,2,76,NaN,38474
top,2016-03-14 20:50:02,Ford_Fiesta,NaN,test,limousine,NaN,manuell,NaN,golf,NaN,NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,2016-04-07 06:17:27
freq,3,76,NaN,25019,12598,NaN,36102,NaN,3900,NaN,NaN,29368,10336,34775,1887,NaN,8
mean,NaN,NaN,5888.935591,NaN,NaN,2004.755421,NaN,117.197158,NaN,125770.101925,5.782251,NaN,NaN,NaN,NaN,50975.745207,NaN
std,NaN,NaN,9059.854754,NaN,NaN,88.643887,NaN,200.649618,NaN,39788.636804,3.685595,NaN,NaN,NaN,NaN,25746.968398,NaN
min,NaN,NaN,1.000000,NaN,NaN,1000.000000,NaN,0.000000,NaN,5000.000000,0.000000,NaN,NaN,NaN,NaN,1067.000000,NaN
25%,NaN,NaN,1200.000000,NaN,NaN,1999.000000,NaN,71.000000,NaN,125000.000000,3.000000,NaN,NaN,NaN,NaN,30657.000000,NaN
50%,NaN,NaN,3000.000000,NaN,NaN,2004.000000,NaN,107.000000,NaN,150000.000000,6.000000,NaN,NaN,NaN,NaN,49716.000000,NaN
75%,NaN,NaN,7490.000000,NaN,NaN,2008.000000,NaN,150.000000,NaN,150000.000000,9.000000,NaN,NaN,NaN,NaN,71665.000000,NaN
max,NaN,NaN,350000.000000,NaN,NaN,9999.000000,NaN,17700.000000,NaN,150000.000000,12.000000,NaN,NaN,NaN,NaN,99998.000000,NaN

`date_crawled` , `ad_created` and `last_seen` are columns containing string values.

In [28]:
print(autos.loc[: , 'date_crawled'].str[:10].value_counts(normalize = True , dropna = False).sort_index())
print('\n')
print(autos.loc[: , 'ad_created'].str[:10].value_counts(normalize = True , dropna = False).sort_index())
print('\n')
print(autos.loc[: , 'last_seen'].str[:10].value_counts(normalize = True , dropna = False).sort_index())

2016-03-05    0.025327
2016-03-06    0.014043
2016-03-07    0.036014
2016-03-08    0.033296
2016-03-09    0.033090
2016-03-10    0.032184
2016-03-11    0.032575
2016-03-12    0.036920
2016-03-13    0.015670
2016-03-14    0.036549
2016-03-15    0.034284
2016-03-16    0.029610
2016-03-17    0.031628
2016-03-18    0.012911
2016-03-19    0.034778
2016-03-20    0.037887
2016-03-21    0.037373
2016-03-22    0.032987
2016-03-23    0.032225
2016-03-24    0.029342
2016-03-25    0.031607
2016-03-26    0.032204
2016-03-27    0.031092
2016-03-28    0.034860
2016-03-29    0.034099
2016-03-30    0.033687
2016-03-31    0.031834
2016-04-01    0.033687
2016-04-02    0.035478
2016-04-03    0.038608
2016-04-04    0.036487
2016-04-05    0.013096
2016-04-06    0.003171
2016-04-07    0.001400
Name: date_crawled, dtype: float64


2015-06-11    0.000021
2015-08-10    0.000021
2015-09-09    0.000021
2015-11-10    0.000021
2015-12-05    0.000021
2015-12-30    0.000021
2016-01-03    0.000021
2016-01-07    0.000021
2016-01-10    0.000041
2016-01-13    0.000021
2016-01-14    0.000021
2016-01-16    0.000021
2016-01-22    0.000021
2016-01-27    0.000062
2016-01-29    0.000021
2016-02-01    0.000021
2016-02-02    0.000041
2016-02-05    0.000041
2016-02-07    0.000021
2016-02-08    0.000021
2016-02-09    0.000021
2016-02-11    0.000021
2016-02-12    0.000041
2016-02-14    0.000041
2016-02-16    0.000021
2016-02-17    0.000021
2016-02-18    0.000041
2016-02-19    0.000062
2016-02-20    0.000041
2016-02-21    0.000062
                ...
2016-03-09    0.033151
2016-03-10    0.031895
2016-03-11    0.032904
2016-03-12    0.036755
2016-03-13    0.017008
2016-03-14    0.035190
2016-03-15    0.034016
2016-03-16    0.030125
2016-03-17    0.031278
2016-03-18    0.013590
2016-03-19    0.033687
2016-03-20    0.037949
2016-03-21    0.037579
2016-03-22    0.032801
2016-03-23    0.032060
2016-03-24    0.029280
2016-03-25    0.031751
2016-03-26    0.032266
2016-03-27    0.030989
2016-03-28    0.034984
2016-03-29    0.034037
2016-03-30    0.033501
2016-03-31    0.031875
2016-04-01    0.033687
2016-04-02    0.035149
2016-04-03    0.038855
2016-04-04    0.036858
2016-04-05    0.011819
2016-04-06    0.003253
2016-04-07    0.001256
Name: ad_created, Length: 76, dtype: float64


2016-03-05    0.001071
2016-03-06    0.004324
2016-03-07    0.005395
2016-03-08    0.007413
2016-03-09    0.009595
2016-03-10    0.010666
2016-03-11    0.012375
2016-03-12    0.023783
2016-03-13    0.008895
2016-03-14    0.012602
2016-03-15    0.015876
2016-03-16    0.016452
2016-03-17    0.028086
2016-03-18    0.007351
2016-03-19    0.015834
2016-03-20    0.020653
2016-03-21    0.020632
2016-03-22    0.021373
2016-03-23    0.018532
2016-03-24    0.019767
2016-03-25    0.019211
2016-03-26    0.016802
2016-03-27    0.015649
2016-03-28    0.020859
2016-03-29    0.022341
2016-03-30    0.024771
2016-03-31    0.023783
2016-04-01    0.022794
2016-04-02    0.024915
2016-04-03    0.025203
2016-04-04    0.024483
2016-04-05    0.124761
2016-04-06    0.221806
2016-04-07    0.131947
Name: last_seen, dtype: float64

Checked on the cell above, the following conclusions are met:

- Whole `date_crawled` column has ben introduced on march and april of 2016.
- However as it can be checked on `ad_created` column, the ads were created before de date crawled.
- The `last_seen` column shows that all the cars were sold or at least stoped advertising on april of 2016.

In [29]:
autos.loc[: , 'registration_year'].describe()

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

According to the `registration_year` column some things to remark:

- There are some null or nan values on the column. 
- There are some outlyers, as the max year is 9999 and this is not reached yet. Same happens with the minimum.

As the registration year has to be before the car registering on the listing, the registration year could not be bigger than 2016.

In addition, realitically the earliest data would not be lower than 1900.

In [30]:
autos.loc[(autos.loc[: , 'registration_year'] >= 1900 ) & (autos.loc[: , 'registration_year'] <= 2016) , 'registration_year'].value_counts(normalize = True)

2000    0.067608
2005    0.062895
1999    0.062060
2004    0.057904
2003    0.057818
2006    0.057197
2001    0.056468
2002    0.053255
1998    0.050620
2007    0.048778
2008    0.047450
2009    0.044665
1997    0.041794
2011    0.034768
2010    0.034040
1996    0.029412
2012    0.028063
1995    0.026285
2016    0.026135
2013    0.017202
2014    0.014203
1994    0.013474
1993    0.009104
2015    0.008397
1992    0.007926
1990    0.007433
1991    0.007262
1989    0.003727
1988    0.002892
1985    0.002035
          ...
1966    0.000471
1976    0.000450
1969    0.000407
1975    0.000386
1965    0.000364
1964    0.000257
1963    0.000171
1959    0.000129
1961    0.000129
1910    0.000107
1956    0.000086
1958    0.000086
1937    0.000086
1962    0.000086
1950    0.000064
1954    0.000043
1941    0.000043
1951    0.000043
1934    0.000043
1957    0.000043
1955    0.000043
1953    0.000021
1943    0.000021
1929    0.000021
1939    0.000021
1938    0.000021
1948    0.000021
1927    0.000021
1931    0.000021
1952    0.000021
Name: registration_year, Length: 78, dtype: float64

In [31]:
autos = autos.loc[(autos.loc[: , 'registration_year'] >= 1900 ) & (autos.loc[: , 'registration_year'] <= 2016) , :]

### 3.7. Car brand exploration

Firstly, the most common brands are taken. Only the ones that have a 5 % on average.

In [32]:
autos.loc[: , 'brand'].value_counts(normalize = True)

volkswagen        0.211264
bmw               0.110045
opel              0.107581
mercedes_benz     0.096463
audi              0.086566
ford              0.069900
renault           0.047150
peugeot           0.029841
fiat              0.025642
seat              0.018273
skoda             0.016409
nissan            0.015274
mazda             0.015188
smart             0.014160
citroen           0.014010
toyota            0.012703
hyundai           0.010025
sonstige_autos    0.009811
volvo             0.009147
mini              0.008762
mitsubishi        0.008226
honda             0.007840
kia               0.007069
alfa_romeo        0.006641
porsche           0.006127
suzuki            0.005934
chevrolet         0.005698
chrysler          0.003513
dacia             0.002635
daihatsu          0.002506
jeep              0.002271
subaru            0.002142
land_rover        0.002099
saab              0.001649
jaguar            0.001564
daewoo            0.001500
trabant           0.001392
rover             0.001328
lancia            0.001071
lada              0.000578
Name: brand, dtype: float64

In [33]:
brands_list = autos.loc[: , 'brand'].value_counts(normalize = True)
common_brands = brands_list[brands_list > 0.05].index
print(common_brands)

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford'], dtype='object')

Later, the number of cars that they have got is stored in a dictionary in order to have the numbers.

In [34]:
brands_num = {}
for brand in common_brands:
    brands_num[brand] = autos.loc[autos.loc[: , 'brand'] == brand , 'brand'].value_counts()[0]
    
    
    #brands_num[vect[0]] = vect[1]

In [35]:
print(brands_num)

{'volkswagen': 9862, 'bmw': 5137, 'opel': 5022, 'mercedes_benz': 4503, 'audi': 4041, 'ford': 3263}

As seen, volkswagen cars are the most popular ones which have approximately doubled the sum of the cars which have got the second and the third one.

Now the mean prices of the common brands are going to be exposed:

In [36]:
mean_prices = {}
for brand in common_brands:
    mean_prices[brand] = int(autos.loc[autos.loc[: , 'brand'] == brand , 'price_dollar'].sum() / brands_num[brand])

In [37]:
print(mean_prices)

{'volkswagen': 5402, 'bmw': 8332, 'opel': 2975, 'mercedes_benz': 8628, 'audi': 9336, 'ford': 3749}

As studied, here are the mean prices of each popular brand:

- Audi, Mercedes Bez and BMW are the most expensive ones.
- Ford and Opel are the cheapest.
- Volkwagen is the one which is in the middle. This could explain why it is the most sold brand according to one of the previous cells.

### 3.8. Exploring the mileage

For that we are going to create a dataframe object, in order to be able to visualize all the data on a good way.

So firstly, the mean prices should be converted to a series data type.

In [38]:
top_brand = pd.Series(mean_prices)

In [39]:
top_brand

volkswagen       5402
bmw              8332
opel             2975
mercedes_benz    8628
audi             9336
ford             3749
dtype: int64

After that, a dataframe object is created, with a column which is the series created before.

In [40]:
top_brand_df = pd.DataFrame(top_brand , columns = ['mean_price'])

In [41]:
top_brand_df

               mean_price
volkswagen           5402
bmw                  8332
opel                 2975
mercedes_benz        8628
audi                 9336
ford                 3749

Above is the dataframe created.

After that, the mean mileage for each car should be obtained.

In [42]:
mean_mileage = {}
for brand in common_brands:
    mean_mileage[brand] = int(autos.loc[autos.loc[: , 'brand'] == brand , 'odometer_km'].sum() / brands_num[brand])

In [43]:
mean_mileage

{'volkswagen': 128707,
 'bmw': 132572,
 'opel': 129310,
 'mercedes_benz': 130788,
 'audi': 129157,
 'ford': 124266}

Introducing the mean mileage to a series for then assigning to a new column of the dataframe, at the end, we obtain a dataframe with two columns.

In [44]:
mean_mileage_s = pd.Series(mean_mileage)

In [45]:
top_brand_df.loc[: , 'mean_mileage'] = mean_mileage_s

In [46]:
top_brand_df

               mean_price  mean_mileage
volkswagen           5402        128707
bmw                  8332        132572
opel                 2975        129310
mercedes_benz        8628        130788
audi                 9336        129157
ford                 3749        124266

Looking to the dataframe. Can be said, that the mean mileages are more or less equal. However, other thing that could be taken is that the most expensive cars have slightly higher mean mileage than the other ones.

In [47]:
top_brand_df.loc[: , 'mean_mileage'].describe()

count         6.000000
mean     129133.333333
std        2773.691235
min      124266.000000
25%      128819.500000
50%      129233.500000
75%      130418.500000
max      132572.000000
Name: mean_mileage, dtype: float64

## 4. Personal work

At this point, the guided project has finished. However we will continue to study the dataset more in depth, looking for this different aspects:

- Data cleaning steps:
    - Identify categorical data on german words, translate them and map the values to their english counterparts.
    - Convert dates to uniform numeric data
    - Check if there is any new columns that you could extract from name column.
- Analysis next steps:
    - Find the most common brand / model combinations.
    - Split the odometer_km into groups and use aggregation to see if there is any pattern with prices based on milage.
    - How much cheaper are the damaged cars than their non-damaged counterparts?

### 4.1 Data cleaning steps:

In [48]:
autos

,date_crawled,name,price_dollar,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatik,150,voyager,150000,4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998,manuell,90,golf,150000,12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,250,test,NaN,2000,manuell,0,arosa,150000,10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997,manuell,90,megane,150000,7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,350,control,NaN,2000,NaN,0,NaN,150000,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,kleinwagen,2010,automatik,71,fortwo,50000,9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,1350,control,limousine,1999,manuell,101,a3,150000,11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,kleinwagen,2007,manuell,75,clio,150000,9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,350,test,kombi,1999,manuell,101,vectra,150000,5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990,manuell,205,scirocco,150000,6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995,manuell,150,3er,150000,0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,kombi,2003,manuell,131,a4,150000,5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manuell,120,NaN,150000,2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90,control,kombi,1996,manuell,116,NaN,150000,4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,777,control,kleinwagen,1992,manuell,54,polo,125000,2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
28,2016-03-19 21:56:19,MINI_Cooper_D,5250,control,kleinwagen,2007,manuell,110,cooper,150000,7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,kombi,2004,automatik,204,e_klasse,150000,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,80,test,kleinwagen,2002,manuell,60,2_reihe,150000,6,benzin,peugeot,ja,2016-03-14 00:00:00,57076,2016-03-14 11:47:31
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,2850,test,kombi,2002,automatik,218,c_klasse,150000,7,benzin,mercedes_benz,nein,2016-03-14 00:00:00,41065,2016-03-16 07:19:04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatik,90,andere,150000,9,diesel,mercedes_benz,nein,2016-04-01 00:00:00,40227,2016-04-05 13:16:35
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005,manuell,136,x_trail,150000,5,diesel,nissan,nein,2016-03-17 00:00:00,17379,2016-03-25 23:18:15
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,950,test,kleinwagen,2001,manuell,50,lupo,150000,4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatik,150,vito,150000,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabrio,2004,manuell,163,slk,150000,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,kleinwagen,2012,automatik,88,jazz,100000,11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,kombi,1992,automatik,150,80,150000,12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003,manuell,116,c_klasse,150000,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,900,control,limousine,1996,automatik,136,e_klasse,150000,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,400,control,kombi,1995,manuell,105,escort,125000,3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,kombi,1998,manuell,115,astra,150000,12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,kleinwagen,2004,manuell,0,fabia,90000,7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,600,test,kleinwagen,1999,manuell,101,focus,150000,4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995,automatik,0,NaN,150000,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,9550,control,coupe,2001,manuell,231,3er,150000,10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,kleinwagen,1997,manuell,0,polo,150000,5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,500,control,NaN,2016,manuell,0,twingo,150000,0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,kleinwagen,1997,manuell,0,NaN,150000,7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,kombi,2001,automatik,299,a6,150000,1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabrio,1996,manuell,75,astra,150000,5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,1250,control,limousine,1996,manuell,101,vectra,150000,1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

#### 4.1.1 Identifying German words

Looking to the `unrepaired_damage` column we are able to check the following thing.

In [49]:
autos.loc[: , 'unrepaired_damage'].value_counts(dropna = False)

nein    33834
NaN      8307
ja       4540
Name: unrepaired_damage, dtype: int64

There are three possible values:

- ***nein:*** **No** in English.
- ***ja:*** **Yes** in English.
- ***NaN:*** Not a number. So it will mean that this information is **Unknown**.

For that we will create a dictionary, which contains all the mapping.

In [50]:
unrepaired_damage_values = { 'nein' : 'no' , 'ja' : 'yes' , np.nan : 'unknown'}

In [51]:
autos.loc[: , 'unrepaired_damage']= autos.loc[: , 'unrepaired_damage'].map(unrepaired_damage_values)

In [52]:
autos.loc[: , 'unrepaired_damage'].value_counts(dropna = False)

no         33834
unknown     8307
yes         4540
Name: unrepaired_damage, dtype: int64

#### 4.1.2 Convert dates string to numbers


So we will start with the first column, named `date_crawled`.

In [53]:
autos.loc[: , 'date_crawled'] = autos.loc[: , 'date_crawled'].str.replace('-' , '').str[:7].astype(int)

In [54]:
autos

,date_crawled,name,price_dollar,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016032,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,no,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016040,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,no,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016032,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,no,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016031,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,no,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016040,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,no,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016032,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatik,150,voyager,150000,4,diesel,chrysler,unknown,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016032,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,unknown,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016031,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998,manuell,90,golf,150000,12,diesel,volkswagen,no,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016032,Seat_Arosa,250,test,NaN,2000,manuell,0,arosa,150000,10,NaN,seat,no,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016031,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997,manuell,90,megane,150000,7,benzin,renault,no,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
11,2016031,Mercedes_A140_Motorschaden,350,control,NaN,2000,NaN,0,NaN,150000,0,benzin,mercedes_benz,unknown,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016033,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,kleinwagen,2010,automatik,71,fortwo,50000,9,benzin,smart,no,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016032,Audi_A3_1.6_tuning,1350,control,limousine,1999,manuell,101,a3,150000,11,benzin,audi,no,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016032,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,kleinwagen,2007,manuell,75,clio,150000,9,benzin,renault,unknown,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016040,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,no,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016031,Opel_Vectra_B_Kombi,350,test,kombi,1999,manuell,101,vectra,150000,5,benzin,opel,no,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016032,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990,manuell,205,scirocco,150000,6,benzin,volkswagen,no,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016032,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995,manuell,150,3er,150000,0,benzin,bmw,unknown,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016031,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,no,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016030,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,kombi,2003,manuell,131,a4,150000,5,diesel,audi,unknown,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016030,Porsche_911_Carrera_4S_Cabrio,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,no,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016032,MINI_Cooper_S_Cabrio,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,no,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016031,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manuell,120,NaN,150000,2,diesel,peugeot,no,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016040,BMW_535i_xDrive_Sport_Aut.,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,no,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016032,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90,control,kombi,1996,manuell,116,NaN,150000,4,benzin,ford,yes,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016040,Volkswagen_Polo_Fox,777,control,kleinwagen,1992,manuell,54,polo,125000,2,benzin,volkswagen,no,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
28,2016031,MINI_Cooper_D,5250,control,kleinwagen,2007,manuell,110,cooper,150000,7,diesel,mini,yes,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016040,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,kombi,2004,automatik,204,e_klasse,150000,10,diesel,mercedes_benz,no,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
30,2016031,Peugeot_206_Unfallfahrzeug,80,test,kleinwagen,2002,manuell,60,2_reihe,150000,6,benzin,peugeot,yes,2016-03-14 00:00:00,57076,2016-03-14 11:47:31
31,2016031,Noch_gut_erhaltenen_C_320,2850,test,kombi,2002,automatik,218,c_klasse,150000,7,benzin,mercedes_benz,no,2016-03-14 00:00:00,41065,2016-03-16 07:19:04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49968,2016040,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatik,90,andere,150000,9,diesel,mercedes_benz,no,2016-04-01 00:00:00,40227,2016-04-05 13:16:35
49969,2016031,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005,manuell,136,x_trail,150000,5,diesel,nissan,no,2016-03-17 00:00:00,17379,2016-03-25 23:18:15
49970,2016032,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,no,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016032,W.Lupo_1.0,950,test,kleinwagen,2001,manuell,50,lupo,150000,4,benzin,volkswagen,no,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016032,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatik,150,vito,150000,10,diesel,mercedes_benz,yes,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016032,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabrio,2004,manuell,163,slk,150000,11,benzin,mercedes_benz,no,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49975,2016032,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,kleinwagen,2012,automatik,88,jazz,100000,11,hybrid,honda,no,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016031,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,kombi,1992,automatik,150,80,150000,12,benzin,audi,no,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016033,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003,manuell,116,c_klasse,150000,2,diesel,mercedes_benz,no,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016040,Mercedes_Benz_E_200_Classic,900,control,limousine,1996,automatik,136,e_klasse,150000,9,benzin,mercedes_benz,yes,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016032,Volkswagen_Polo_1.6_TDI_Style,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,no,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016031,Ford_Escort_Turnier_16V,400,control,kombi,1995,manuell,105,escort,125000,3,benzin,ford,unknown,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016031,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,kombi,1998,manuell,115,astra,150000,12,benzin,opel,no,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016032,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,kleinwagen,2004,manuell,0,fabia,90000,7,benzin,skoda,unknown,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016030,Ford_focus_99,600,test,kleinwagen,1999,manuell,101,focus,150000,4,benzin,ford,unknown,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49985,2016040,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995,automatik,0,NaN,150000,0,benzin,volkswagen,unknown,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016040,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,no,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016032,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,no,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016032,BMW_330_Ci,9550,control,coupe,2001,manuell,231,3er,150000,10,benzin,bmw,no,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016031,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,kleinwagen,1997,manuell,0,polo,150000,5,benzin,volkswagen,yes,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016032,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,no,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016030,Kleinwagen,500,control,NaN,2016,manuell,0,twingo,150000,0,benzin,renault,unknown,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016031,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,no,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016031,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,kleinwagen,1997,manuell,0,NaN,150000,7,benzin,audi,unknown,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016032,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,kombi,2001,automatik,299,a6,150000,1,benzin,audi,no,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016032,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,no,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016032,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabrio,1996,manuell,75,astra,150000,5,benzin,opel,no,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016040,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,no,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016030,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,no,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016031,Opel_Vectra_1.6_16V,1250,control,limousine,1996,manuell,101,vectra,150000,1,benzin,opel,no,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

Now the `ad_created`.

In [55]:
autos.loc[: , 'ad_created'] = autos.loc[: , 'ad_created'].str.replace('-' , '').str[:7].astype(int)

In [56]:
autos

,date_crawled,name,price_dollar,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016032,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,no,2016032,79588,2016-04-06 06:45:54
1,2016040,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,no,2016040,71034,2016-04-06 14:45:08
2,2016032,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,no,2016032,35394,2016-04-06 20:15:37
3,2016031,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,no,2016031,33729,2016-03-15 03:16:28
4,2016040,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,no,2016040,39218,2016-04-01 14:38:50
5,2016032,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatik,150,voyager,150000,4,diesel,chrysler,unknown,2016032,22962,2016-04-06 09:45:21
6,2016032,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,unknown,2016032,31535,2016-03-23 02:48:59
7,2016031,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998,manuell,90,golf,150000,12,diesel,volkswagen,no,2016031,53474,2016-04-07 03:17:32
8,2016032,Seat_Arosa,250,test,NaN,2000,manuell,0,arosa,150000,10,NaN,seat,no,2016032,7426,2016-03-26 18:18:10
9,2016031,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997,manuell,90,megane,150000,7,benzin,renault,no,2016031,15749,2016-04-06 10:46:35
11,2016031,Mercedes_A140_Motorschaden,350,control,NaN,2000,NaN,0,NaN,150000,0,benzin,mercedes_benz,unknown,2016031,17498,2016-03-16 18:45:34
12,2016033,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,kleinwagen,2010,automatik,71,fortwo,50000,9,benzin,smart,no,2016033,34590,2016-04-06 14:17:52
13,2016032,Audi_A3_1.6_tuning,1350,control,limousine,1999,manuell,101,a3,150000,11,benzin,audi,no,2016032,12043,2016-04-01 14:17:13
14,2016032,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,kleinwagen,2007,manuell,75,clio,150000,9,benzin,renault,unknown,2016032,81737,2016-04-01 15:46:47
15,2016040,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,no,2016040,61276,2016-04-02 21:10:48
16,2016031,Opel_Vectra_B_Kombi,350,test,kombi,1999,manuell,101,vectra,150000,5,benzin,opel,no,2016031,57299,2016-03-18 05:29:37
17,2016032,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990,manuell,205,scirocco,150000,6,benzin,volkswagen,no,2016032,74821,2016-04-05 20:46:26
18,2016032,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995,manuell,150,3er,150000,0,benzin,bmw,unknown,2016032,54329,2016-04-02 12:16:41
19,2016031,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,no,2016031,40878,2016-03-17 14:45:58
20,2016030,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,kombi,2003,manuell,131,a4,150000,5,diesel,audi,unknown,2016030,53913,2016-03-07 05:46:46
21,2016030,Porsche_911_Carrera_4S_Cabrio,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,no,2016030,65428,2016-04-05 23:46:19
22,2016032,MINI_Cooper_S_Cabrio,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,no,2016032,44789,2016-04-01 06:45:30
23,2016031,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manuell,120,NaN,150000,2,diesel,peugeot,no,2016031,30900,2016-03-17 08:45:17
24,2016040,BMW_535i_xDrive_Sport_Aut.,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,no,2016040,22547,2016-04-07 13:16:50
25,2016032,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90,control,kombi,1996,manuell,116,NaN,150000,4,benzin,ford,yes,2016032,27574,2016-04-01 05:16:49
26,2016040,Volkswagen_Polo_Fox,777,control,kleinwagen,1992,manuell,54,polo,125000,2,benzin,volkswagen,no,2016040,38110,2016-04-05 23:46:48
28,2016031,MINI_Cooper_D,5250,control,kleinwagen,2007,manuell,110,cooper,150000,7,diesel,mini,yes,2016031,15745,2016-04-07 14:58:48
29,2016040,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,kombi,2004,automatik,204,e_klasse,150000,10,diesel,mercedes_benz,no,2016040,47638,2016-04-02 12:45:44
30,2016031,Peugeot_206_Unfallfahrzeug,80,test,kleinwagen,2002,manuell,60,2_reihe,150000,6,benzin,peugeot,yes,2016031,57076,2016-03-14 11:47:31
31,2016031,Noch_gut_erhaltenen_C_320,2850,test,kombi,2002,automatik,218,c_klasse,150000,7,benzin,mercedes_benz,no,2016031,41065,2016-03-16 07:19:04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49968,2016040,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatik,90,andere,150000,9,diesel,mercedes_benz,no,2016040,40227,2016-04-05 13:16:35
49969,2016031,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005,manuell,136,x_trail,150000,5,diesel,nissan,no,2016031,17379,2016-03-25 23:18:15
49970,2016032,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,no,2016032,14947,2016-04-07 04:17:34
49971,2016032,W.Lupo_1.0,950,test,kleinwagen,2001,manuell,50,lupo,150000,4,benzin,volkswagen,no,2016032,65197,2016-03-29 20:41:51
49972,2016032,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatik,150,vito,150000,10,diesel,mercedes_benz,yes,2016032,65326,2016-03-28 11:28:18
49973,2016032,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabrio,2004,manuell,163,slk,150000,11,benzin,mercedes_benz,no,2016032,53567,2016-03-27 08:25:24
49975,2016032,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,kleinwagen,2012,automatik,88,jazz,100000,11,hybrid,honda,no,2016032,84385,2016-04-05 19:45:34
49976,2016031,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,kombi,1992,automatik,150,80,150000,12,benzin,audi,no,2016031,36100,2016-04-07 06:16:44
49977,2016033,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003,manuell,116,c_klasse,150000,2,diesel,mercedes_benz,no,2016033,33739,2016-04-06 12:16:11
49978,2016040,Mercedes_Benz_E_200_Classic,900,control,limousine,1996,automatik,136,e_klasse,150000,9,benzin,mercedes_benz,yes,2016040,24405,2016-04-06 12:44:20
49979,2016032,Volkswagen_Polo_1.6_TDI_Style,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,no,2016032,48455,2016-04-07 01:45:12
49980,2016031,Ford_Escort_Turnier_16V,400,control,kombi,1995,manuell,105,escort,125000,3,benzin,ford,unknown,2016031,56218,2016-04-06 17:16:49
49981,2016031,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,kombi,1998,manuell,115,astra,150000,12,benzin,opel,no,2016031,86859,2016-04-05 17:21:46
49982,2016032,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,kleinwagen,2004,manuell,0,fabia,90000,7,benzin,skoda,unknown,2016032,45884,2016-03-29 18:51:08
49983,2016030,Ford_focus_99,600,test,kleinwagen,1999,manuell,101,focus,150000,4,benzin,ford,unknown,2016030,52477,2016-03-09 06:16:08
49985,2016040,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995,automatik,0,NaN,150000,0,benzin,volkswagen,unknown,2016040,30900,2016-04-06 15:17:52
49986,2016040,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,no,2016040,73527,2016-04-06 23:16:00
49987,2016032,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,no,2016032,94362,2016-03-26 22:46:06
49988,2016032,BMW_330_Ci,9550,control,coupe,2001,manuell,231,3er,150000,10,benzin,bmw,no,2016032,83646,2016-04-07 02:17:40
49989,2016031,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,kleinwagen,1997,manuell,0,polo,150000,5,benzin,volkswagen,yes,2016031,21244,2016-03-12 10:17:55
49990,2016032,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,no,2016032,58239,2016-04-06 22:46:57
49991,2016030,Kleinwagen,500,control,NaN,2016,manuell,0,twingo,150000,0,benzin,renault,unknown,2016030,61350,2016-03-06 18:24:19
49992,2016031,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,no,2016031,68642,2016-03-13 01:44:51
49993,2016031,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,kleinwagen,1997,manuell,0,NaN,150000,7,benzin,audi,unknown,2016031,65203,2016-04-06 19:46:53
49994,2016032,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,kombi,2001,automatik,299,a6,150000,1,benzin,audi,no,2016032,46537,2016-04-06 08:16:39
49995,2016032,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,no,2016032,82131,2016-04-01 13:47:40
49996,2016032,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabrio,1996,manuell,75,astra,150000,5,benzin,opel,no,2016032,44807,2016-04-02 14:18:02
49997,2016040,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,no,2016040,73430,2016-04-04 11:47:27
49998,2016030,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,no,2016030,35683,2016-04-05 16:45:07
49999,2016031,Opel_Vectra_1.6_16V,1250,control,limousine,1996,manuell,101,vectra,150000,1,benzin,opel,no,2016031,45897,2016-04-06 21:18:48

Now the `last_seen`.

In [57]:
autos.loc[: , 'last_seen'] = autos.loc[: , 'last_seen'].str.replace('-' , '').str[:7].astype(int)

In [58]:
autos

,date_crawled,name,price_dollar,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016032,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,no,2016032,79588,2016040
1,2016040,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,no,2016040,71034,2016040
2,2016032,Volkswagen_Golf_1.6_United,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,no,2016032,35394,2016040
3,2016031,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,no,2016031,33729,2016031
4,2016040,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,no,2016040,39218,2016040
5,2016032,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatik,150,voyager,150000,4,diesel,chrysler,unknown,2016032,22962,2016040
6,2016032,VW_Golf_III_GT_Special_Electronic_Green_Metall...,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,unknown,2016032,31535,2016032
7,2016031,Golf_IV_1.9_TDI_90PS,1990,control,limousine,1998,manuell,90,golf,150000,12,diesel,volkswagen,no,2016031,53474,2016040
8,2016032,Seat_Arosa,250,test,NaN,2000,manuell,0,arosa,150000,10,NaN,seat,no,2016032,7426,2016032
9,2016031,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,590,control,bus,1997,manuell,90,megane,150000,7,benzin,renault,no,2016031,15749,2016040
11,2016031,Mercedes_A140_Motorschaden,350,control,NaN,2000,NaN,0,NaN,150000,0,benzin,mercedes_benz,unknown,2016031,17498,2016031
12,2016033,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,kleinwagen,2010,automatik,71,fortwo,50000,9,benzin,smart,no,2016033,34590,2016040
13,2016032,Audi_A3_1.6_tuning,1350,control,limousine,1999,manuell,101,a3,150000,11,benzin,audi,no,2016032,12043,2016040
14,2016032,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,kleinwagen,2007,manuell,75,clio,150000,9,benzin,renault,unknown,2016032,81737,2016040
15,2016040,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,no,2016040,61276,2016040
16,2016031,Opel_Vectra_B_Kombi,350,test,kombi,1999,manuell,101,vectra,150000,5,benzin,opel,no,2016031,57299,2016031
17,2016032,Volkswagen_Scirocco_2_G60,5500,test,coupe,1990,manuell,205,scirocco,150000,6,benzin,volkswagen,no,2016032,74821,2016040
18,2016032,Verkaufen_mein_bmw_e36_320_i_touring,300,control,bus,1995,manuell,150,3er,150000,0,benzin,bmw,unknown,2016032,54329,2016040
19,2016031,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,no,2016031,40878,2016031
20,2016030,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,kombi,2003,manuell,131,a4,150000,5,diesel,audi,unknown,2016030,53913,2016030
21,2016030,Porsche_911_Carrera_4S_Cabrio,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,no,2016030,65428,2016040
22,2016032,MINI_Cooper_S_Cabrio,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,no,2016032,44789,2016040
23,2016031,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manuell,120,NaN,150000,2,diesel,peugeot,no,2016031,30900,2016031
24,2016040,BMW_535i_xDrive_Sport_Aut.,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,no,2016040,22547,2016040
25,2016032,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,90,control,kombi,1996,manuell,116,NaN,150000,4,benzin,ford,yes,2016032,27574,2016040
26,2016040,Volkswagen_Polo_Fox,777,control,kleinwagen,1992,manuell,54,polo,125000,2,benzin,volkswagen,no,2016040,38110,2016040
28,2016031,MINI_Cooper_D,5250,control,kleinwagen,2007,manuell,110,cooper,150000,7,diesel,mini,yes,2016031,15745,2016040
29,2016040,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,kombi,2004,automatik,204,e_klasse,150000,10,diesel,mercedes_benz,no,2016040,47638,2016040
30,2016031,Peugeot_206_Unfallfahrzeug,80,test,kleinwagen,2002,manuell,60,2_reihe,150000,6,benzin,peugeot,yes,2016031,57076,2016031
31,2016031,Noch_gut_erhaltenen_C_320,2850,test,kombi,2002,automatik,218,c_klasse,150000,7,benzin,mercedes_benz,no,2016031,41065,2016031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49968,2016040,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatik,90,andere,150000,9,diesel,mercedes_benz,no,2016040,40227,2016040
49969,2016031,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,suv,2005,manuell,136,x_trail,150000,5,diesel,nissan,no,2016031,17379,2016032
49970,2016032,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,no,2016032,14947,2016040
49971,2016032,W.Lupo_1.0,950,test,kleinwagen,2001,manuell,50,lupo,150000,4,benzin,volkswagen,no,2016032,65197,2016032
49972,2016032,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatik,150,vito,150000,10,diesel,mercedes_benz,yes,2016032,65326,2016032
49973,2016032,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabrio,2004,manuell,163,slk,150000,11,benzin,mercedes_benz,no,2016032,53567,2016032
49975,2016032,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,kleinwagen,2012,automatik,88,jazz,100000,11,hybrid,honda,no,2016032,84385,2016040
49976,2016031,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,kombi,1992,automatik,150,80,150000,12,benzin,audi,no,2016031,36100,2016040
49977,2016033,Mercedes_Benz_C200_Cdi_W203,5500,control,limousine,2003,manuell,116,c_klasse,150000,2,diesel,mercedes_benz,no,2016033,33739,2016040
49978,2016040,Mercedes_Benz_E_200_Classic,900,control,limousine,1996,automatik,136,e_klasse,150000,9,benzin,mercedes_benz,yes,2016040,24405,2016040
49979,2016032,Volkswagen_Polo_1.6_TDI_Style,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,no,2016032,48455,2016040
49980,2016031,Ford_Escort_Turnier_16V,400,control,kombi,1995,manuell,105,escort,125000,3,benzin,ford,unknown,2016031,56218,2016040
49981,2016031,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,kombi,1998,manuell,115,astra,150000,12,benzin,opel,no,2016031,86859,2016040
49982,2016032,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,kleinwagen,2004,manuell,0,fabia,90000,7,benzin,skoda,unknown,2016032,45884,2016032
49983,2016030,Ford_focus_99,600,test,kleinwagen,1999,manuell,101,focus,150000,4,benzin,ford,unknown,2016030,52477,2016030
49985,2016040,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995,automatik,0,NaN,150000,0,benzin,volkswagen,unknown,2016040,30900,2016040
49986,2016040,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,no,2016040,73527,2016040
49987,2016032,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,no,2016032,94362,2016032
49988,2016032,BMW_330_Ci,9550,control,coupe,2001,manuell,231,3er,150000,10,benzin,bmw,no,2016032,83646,2016040
49989,2016031,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,150,test,kleinwagen,1997,manuell,0,polo,150000,5,benzin,volkswagen,yes,2016031,21244,2016031
49990,2016032,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,no,2016032,58239,2016040
49991,2016030,Kleinwagen,500,control,NaN,2016,manuell,0,twingo,150000,0,benzin,renault,unknown,2016030,61350,2016030
49992,2016031,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,no,2016031,68642,2016031
49993,2016031,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,kleinwagen,1997,manuell,0,NaN,150000,7,benzin,audi,unknown,2016031,65203,2016040
49994,2016032,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,kombi,2001,automatik,299,a6,150000,1,benzin,audi,no,2016032,46537,2016040
49995,2016032,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,no,2016032,82131,2016040
49996,2016032,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabrio,1996,manuell,75,astra,150000,5,benzin,opel,no,2016032,44807,2016040
49997,2016040,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,no,2016040,73430,2016040
49998,2016030,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,no,2016030,35683,2016040
49999,2016031,Opel_Vectra_1.6_16V,1250,control,limousine,1996,manuell,101,vectra,150000,1,benzin,opel,no,2016031,45897,2016040

### 4.2. Analysis steps

#### 4.2.1 Most common brand /model combinations

For doing that, we use the list created before with the most common brands for automotion. With this list, we are able to obtain the combinations of the most succesfull model of the brand on the eBay webpage.

In [62]:
brand_model_combinations = {}
for brand in common_brands:
    brand_model_combinations[brand] = autos.loc[autos.loc[: , 'brand'] == brand , 'model'].value_counts(dropna = False).index[0]

In [63]:
brand_model_combinations

{'volkswagen': 'golf',
 'bmw': '3er',
 'opel': 'corsa',
 'mercedes_benz': 'c_klasse',
 'audi': 'a4',
 'ford': 'focus'}

#### 4.2.2 Odometer groups aggregation

For performing this aggregation. First of all, we check the information which is in the dataset.

It is easy to check the maximum and the minimum value of the data, so with this values we are able to create some groups.

In [64]:
autos.loc[: , 'odometer_km'].describe()

count     46681.000000
mean     125586.855466
std       39852.528628
min        5000.000000
25%      100000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

Those groups are created by ranges of 25k kilometers. So as we will be able to check the change on average of the prices of the cars on the gaps.

In [67]:
odometer_price_study = {}
keys = ['125k-150k' , '100k-125k' , '75k-100k' , '50k-75k' , '25k-50k' , '0-25k' ]
val = 0
for key in keys:
    odometer_price_study[key] = autos.loc[(autos.loc[: , 'odometer_km'] >= (val * 25000)) & (autos.loc[: , 'odometer_km'] < ((val+1) * 25000)) , 'price_dollar'].mean()
    val += 1

In [68]:
odometer_price_study

{'125k-150k': 14483.732466063348,
 '100k-125k': 16041.022479126525,
 '75k-100k': 12290.308041112454,
 '50k-75k': 9032.042322834646,
 '25k-50k': 8132.697278911564,
 '0-25k': 6214.0220300597075}

As a result we can check that the most expensive gap is the gap between 100k km and 125k km. It is strange, because as the km quantities increase the prices should decrease like happens on the last gap.

However, if we check the most expensive gap, and check for the brands, we will see the following.

As the number of kms drop, the amount of cars for sale also increases, having more cars from cheaper brands. So this makes to have a less average of prices.

In [74]:
autos.loc[(autos.loc[: , 'odometer_km'] >= (4 * 25000)) & (autos.loc[: , 'odometer_km'] < ((5) * 25000)) , 'brand'].value_counts()

volkswagen        373
opel              227
bmw               183
mercedes_benz     164
ford              154
audi              134
renault           111
peugeot            71
fiat               66
smart              58
seat               50
nissan             45
sonstige_autos     44
citroen            41
skoda              39
toyota             37
hyundai            31
mini               28
porsche            25
suzuki             24
mazda              21
mitsubishi         20
kia                17
alfa_romeo         12
honda              11
daihatsu            9
chevrolet           9
volvo               8
chrysler            6
lancia              6
jaguar              5
subaru              5
dacia               5
trabant             5
rover               4
land_rover          3
daewoo              3
jeep                2
lada                2
Name: brand, dtype: int64

In [75]:
autos.loc[(autos.loc[: , 'odometer_km'] >= (3 * 25000)) & (autos.loc[: , 'odometer_km'] < ((4) * 25000)) , 'brand'].value_counts()

volkswagen        537
bmw               275
opel              273
ford              246
mercedes_benz     230
audi              189
renault           140
peugeot           112
smart             105
fiat              104
skoda              91
mini               80
nissan             67
citroen            59
seat               56
toyota             51
mazda              46
hyundai            45
suzuki             36
porsche            34
chevrolet          31
honda              30
sonstige_autos     29
kia                29
mitsubishi         22
volvo              21
alfa_romeo         20
dacia              17
chrysler           11
lada                9
daewoo              8
daihatsu            8
jeep                8
trabant             7
subaru              7
land_rover          5
jaguar              4
lancia              4
rover               1
saab                1
Name: brand, dtype: int64

In [76]:
autos.loc[(autos.loc[: , 'odometer_km'] >= (2 * 25000)) & (autos.loc[: , 'odometer_km'] < ((3) * 25000)) , 'brand'].value_counts()

volkswagen        597
mercedes_benz     266
opel              261
ford              255
bmw               235
audi              227
renault           121
smart             117
fiat              107
peugeot           103
mini               86
seat               83
skoda              81
hyundai            77
toyota             71
nissan             69
citroen            62
mazda              59
chevrolet          58
sonstige_autos     56
honda              42
kia                38
porsche            36
suzuki             33
mitsubishi         24
trabant            21
dacia              19
volvo              13
alfa_romeo         13
jeep               11
subaru             10
land_rover         10
daihatsu            9
chrysler            8
jaguar              8
daewoo              7
lada                7
lancia              3
rover               3
saab                2
Name: brand, dtype: int64

#### 4.2.3 Damaged and non-damaged cars price difference

Another thing to study is if damaged car is cheaper than a non damaged car or not. For performing this study, the mean prices of the damaged and non damaged cars are obtained.

In [70]:
avg_price_damaged = autos.loc[autos.loc[: , 'unrepaired_damage'] == 'yes' , 'price_dollar'].mean()
avg_price_non_damaged = autos.loc[autos.loc[: , 'unrepaired_damage'] == 'no' , 'price_dollar'].mean()

In [71]:
print(avg_price_damaged)
print('\n')
print(avg_price_non_damaged)

2241.146035242291


7164.033102796004

Checking the result of the cell above, the non damaged cars prices is much higher than the damaged ones.

In [72]:
times_cheaper_damaged = avg_price_non_damaged / avg_price_damaged

In [73]:
times_cheaper_damaged

3.196593613330288

Here it's seen that the non damaged cars are 3.2 times more expensive than the damaged cars.